language: node_js
node_js:
  - node
  - 10
  - 8
before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm run format:ci
  - npm run lint:ci
  - npm test
after_script: greenkeeper-lockfile-upload
after_success:
  - npm run coveralls
